name: ChestShop
main: ChestShop\Main
api: 3.0.0-ALPHA11
version: 3.1
depend: [EconomyAPI]
commands:
  auctionhouse:
    aliases: ["ah", "auction", "auctionhouse"]
permissions:
   auction.command.opcmd:
    default: op
  auction.command.add:
    default: op
  auction.command.remove:
    default: op
